### ISSUE TITLE
Reusable form styling (examples?)

### ISSUE THREAD

**Issue by PizzaConsole** [mateenagy/vue-formify#11] opened 2024-11-05 20:18 UTC
While I think this library is brilliant, I still find myself getting lost in trying to define a "theme" for all my forms to use across my application. (Something akin to what Formkit would have)

Having a headless form library is great. But everyone is still going to need to style their forms some how. 

For example I enjoy have Formkit groups together their label input and error message, which works well with DaisyUI. I am just having a hard time figuring out how to use the composition API with a custom styled component while keeping typ safety

**Comment by mateenagy** [comment] 2024-11-05 20:51
@PizzaConsole Thank you for the kind words.

Yes this is a disadvantage of headless approach, but because I really focused to create a solid foundation with small bundle size I decided to not have any pre-made component (I had before with the first iteration of the packge) but after some consideration I realised it's too much work and take too much time and of course there is ton of UI libraries out there.

This headless approach will always need some extra work from the developer in term of components. I tried to find a method to make this as easy and simple as possible, that is why it have the `createInput` composable which helps create custom component without any fancy step and it help keeps the type safety.

Here is a basic example:
`CustomComponent.vue`:
```vue
<script lang="ts" setup>
defineProps<{label: string}>();
const value = defineModel<string>();
</script>
<template>
  <div>
    <label>{{ label }}</label>
    <input v-model="value" />
  </div>
</template>
```
`Parent.vue`:
```vue
<script lang="ts" setup>
import { useForm, createInput, ComponentProps } from 'vue-formify';
...
const CustomInput = createInput<ComponentProps<typeof Custom>, PostRequest>(Custom);
...
</script>
<template>
  <Form>
    <CustomInput name="name" label="Label for input" />
  </Form>
</template>
```

This is a very basic approach. You can create more generic so you can create once and use it anywhere across your project.
You can read more about the generic approach [here](https://vue-formify.matenagy.me/docs/composables/use-form/#type-safety-with-createinput-composable)

I close this because it's not a bug but feel free to ask here if you have more question about this topic.

**Closed by mateenagy** 2024-11-05 20:51 UTC

**Comment by mateenagy** [comment] 2024-11-06 18:01
I overlook the `error` part of your comment. If you define the error props in your custom component and use it in the template it will automatically works when error is set for the field.

Here is the updated code:
```vue
<script lang="ts" setup>
defineProps<{
  label: string;
  error?: any;
}>();
const value = defineModel<string>();
</script>
<template>
  <div>
    <label>{{ label }}</label>
    <input v-model="value" />
    <p>{{ error }}</p>
  </div>
</template>
```
